create table RMM_MENU
(
  MENUCODE       VARCHAR2(20) not null,
  MENUNAME       VARCHAR2(100),
  MENUURL        VARCHAR2(200),
  PARENTMENU     VARCHAR2(20),
  MENUORDER      INTEGER,
  MENUCREATETIME TIMESTAMP(6),
  MENUCREATER    VARCHAR2(20)
);

create table RMM_REQUIREMENT
(
  REQUIREMENTCODE VARCHAR2(50) not null,
  REQUIREMENTNAME VARCHAR2(100),
  REMARK          VARCHAR2(500),
  CREATETIME      VARCHAR2(30),
  CREATOR         VARCHAR2(30),
  STARTDATE       VARCHAR2(30),
  ENDDATE         VARCHAR2(30),
  STATUS          INTEGER,
  DEPT            VARCHAR2(30),
  PRESENTER       VARCHAR2(30),
  PARENTCODE      VARCHAR2(50),
  CLOSETIME       VARCHAR2(30)
);

create table RMM_USER
(
  USERCODE   VARCHAR2(20) not null,
  USERNAME   VARCHAR2(30),
  CREATETIME TIMESTAMP(6),
  CREATER    VARCHAR2(20),
  PASSWORD   VARCHAR2(120),
  USERTYPE   INTEGER,
  USERSTATUS INTEGER
);

create table RMM_USER_MENU
(
  USERCODE   VARCHAR2(20),
  MENUCODE   VARCHAR2(20),
  PARENTMENU VARCHAR2(20),
  MENUORDER  INTEGER
);

