create table RMM_USER
(
  USERCODE   VARCHAR2(20) not null,
  USERNAME   VARCHAR2(30),
  CREATETIME TIMESTAMP(6),
  CREATER    VARCHAR2(20),
  PASSWORD   VARCHAR2(120),
  USERTYPE   INTEGER,
  USERSTATUS INTEGER
)