create table RMM_MENU
(
  MENUCODE       VARCHAR2(20) not null,
  MENUNAME       VARCHAR2(100),
  MENUURL        VARCHAR2(200),
  PARENTMENU     VARCHAR2(20),
  MENUORDER      INTEGER,
  MENUCREATETIME TIMESTAMP(6),
  MENUCREATER    VARCHAR2(20),
  MENUSTATUS     INTEGER
)