create table RMM_TASK
(
  TASKCODE        VARCHAR2(50) not null,
  TASKNAME        VARCHAR2(50),
  REMARK          VARCHAR2(500),
  STARTTIME       VARCHAR2(30),
  ENDTIME         VARCHAR2(30),
  STATUS          INTEGER,
  TASKTYPE        INTEGER,
  REQUIREMENTCODE VARCHAR2(50),
  TASKGROUP       VARCHAR2(20),
  PLANMANHAUR     INTEGER,
  MANHAUR         INTEGER,
  USERCODE        VARCHAR2(30),
  SIGNTIME        VARCHAR2(30)
)