create table RMM_LOG
(
  LOGCODE         VARCHAR2(30),
  LOGTIME         VARCHAR2(30),
  REQUIREMENTCODE VARCHAR2(30),
  TASKCODE        VARCHAR2(30),
  LOGCREATOR      VARCHAR2(30),
  LOGTEXT         VARCHAR2(500)
)